### ISSUE TITLE
Is it possible to use this sensors without micro controller?

### ISSUE THREAD

**Issue by happytm** [ftjuh/RCWL_1X05#1]
Thank you for digging all information about these sensors? 

I like the size and extra interfaces of these sensors. I was wondering if it is some how possible to pair these sensors with cheap RF 433 wireless transmitters like: https://lastminuteengineers.com/433mhz-rf-wireless-arduino-tutorial/  without using micro controller for simple battery powered wireless application.

Thanks.

**Comment by ftjuh** [comment]
Both devices are of little use without a controlling device. So, no, you'll need a microcontroller.

Anyway, please note that issues are for reporting problems with this repository. Please use the discussions page or a forum with a larger audience like arduino.cc for general questions like these.
