### ISSUE TITLE
can this sensors be used as transmitters or receivers only ? 

### ISSUE THREAD

**Issue by susano254** [ftjuh/RCWL_1X05#2]
I am trying to make a 3d trilateration using the hc-sr04 and came across these sensors with the usual hcsr04 we just cover the transmitter side on the receiver 
But I think a single module like the RCWL_1005 will be more compact for my project so my question is can it be configured to only transmit or receive ?

**Comment by ftjuh** [comment]
I think in serial mode it should work just as the HC-SR04.

PS: please use issues only to report problems or raise questions concerning my code, use discussions  otherwise.
